### ISSUE TITLE
[feature] : Rename package to AFMReader

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/AFMReader#43]
### Is your feature request related to a problem?

It has been suggested by Alice that this repo be renamed to AFMFileFormats as this may be more representative. Is this possible? Are there metadata that cannot change? Likely the PyPI identifier?

### Describe the solution you would like.

Rename the repo to afmfileformats along with the PyPI identifier if possible. Discuss before doing it.

### Describe the alternatives you have considered.

Not renaming it if this isn't possible or if remnants of the old name would cause confusion for users.

## Tasks

+ [x] Rename GitHub repository (and update local clones configuration of `origin` to point to the renamed repository).
+ [x] Update package...
  + [x] `pyproject.toml`
  + [x] ~`CITATION.cff`~ (don't currently have one though!).
  + [x] `topofileformats` > `AFMReader` for package directory.
  + [x] Update all `import topofileformats` to `import AFMReader` (files include `AFMReader/*.py`, `tests/test_*.py`, `README.md`, `examples/example_01.ipynb`).
+ [x] Upload renamed package `AFMReader` to PyPI
+ [x] Update `topofileformats` to have a single dependency `AFMReader` so that the new package is installed if anyone tries to install the old package.
  + [x] ~~Publish updated package to PyPI~~. **Opted to delete `topofileformats` from PyPI** completed by @SylviaWhittle 2024-06-05 15:22
+ [x] ~~Update `TopoStats` to depend on `AFMReader` rather than `topofileformats`~~ see #22 instead.

**Comment by ns-rse** [comment]
I've mentioned before I think the package name could be more descriptive.

I'm not a fan of the `fileformats` component as that implies it relates to a definition of file formats or file specifications.

What the package is doing is _reading_ files of different formats so my suggestion for an appropriate name would be `AFMReader`.

With regards to how to rename...

+ [ ] Rename GitHub repository (and update local clones configuration of `origin` to point to the renamed repository).
+ [ ] Update package Metadata in...
  + [ ] `pyproject.toml`
  + [ ] ~`CITATION.cff`~ (don't currently have one though!).

With PyPI you can't rename packages. You have to upload a new package and have the old one point to the new. The [simonw/pypi-rename: Cookiecutter template for creating renamed PyPI packages](https://github.com/simonw/pypi-rename) can help here it seems.

Technically the new one is a very simple package that has a single dependency, the new package so when people `pip install topofileformats` it would install `AFMReader` (if that is the name of the new package).

A brief search threw up [`afmformats`](https://afmformats.readthedocs.io/en/stable/) which looks like it is a similar package. There may be others and perhaps looking to collaborate might be something to consider (e.g. we're using the `igor2` and `pySPM` packages).

**Comment by ns-rse** [comment]
If you already have a `git clone` of this repository and wish to continue using it now that it has been renamed you need to edit the `.git/config` file in the repository to change `url = git@github.com:AFM-SPM/topofileformats.git` to `url = git@github.com:AFM-SPM/AFMReader.git`...

### Before

```
[remote "origin"]
	url = git@github.com:AFM-SPM/AFMReader.git
```

### After

```
[remote "origin"]
	url = git@github.com:AFM-SPM/topofileformats.git
```


### Not Essential but Sensible

It's not essential but it would be sensible to also rename the cloned directory.  Assuming you are on the command line and the path to the cloned directory is `~/work/git/hub/AFM-SPM/topofileformats` you should change it to `~/work/git/hub/AFM-SPM/AFMReader`.

```bash
mv ~/work/git/hub/AFM-SPM/topofileformats ~/work/git/hub/AFM-SPM/AFMReader
```

**Comment by alicepyne** [comment]
Is this now done?

**Comment by ns-rse** [comment]
Closing, [AFMReader v0.0.1](https://pypi.org/project/AFMReader/) is on PyPI and `topofileformats` has been removed from PyPI to avoid confusion.
